### ISSUE TITLE
Crash on startup with BClib

### ISSUE THREAD

**Issue by HacoKavanah** [gudenau/minecraft-MoreTags#14]
[latest (2).log](https://github.com/gudenau/minecraft-MoreTags/files/8404628/latest.2.log)

I sent this file to the author of BClib, they said this crash is on your end.

**Comment by gudenau** [comment]
It's both sides, I'm working on a fix already.

**Comment by Sunconure11** [comment]
https://github.com/paulevsGitch/BCLib/issues/127

**Comment by paulevsGitch** [comment]
Issue 127 was about wrong mod compat, proper issue is [this](https://github.com/paulevsGitch/BCLib/issues/128)

**Comment by Sunconure11** [comment]
@gudenau Any news on this?

**Comment by Laifsyn** [comment]
I saw the 3.0.3 update. Apparently is still crashing
	- bclib 1.4.3
	- moretags 3.0.3
https://pastebin.com/mTb0Av94
Removing Paulev's mods do however allow me to start minecraft

**Comment by gudenau** [comment]
Sorry, forgot to actually release 3.0.4, it should fix this problem.
