### ISSUE TITLE
More Tags v3.0.4 still crashes with BCLib

### ISSUE THREAD

**Issue by SharkieTV** [gudenau/minecraft-MoreTags#15]
I see the Issue in #130 is closed but the new version still doesn't fix the issue with BCLIb. Only fix is to remove Paradise Lost or BCLIB and its mods.

https://pastebin.com/WzbWWNda

**Comment by skxrlxt** [comment]
I'm having the same problem

**Comment by paulevsGitch** [comment]
Update your BClib to latest, it will fix issue
