### ISSUE TITLE
Farmland-related crash

### ISSUE THREAD

**Issue by Sunconure11** [gudenau/minecraft-MoreTags#17]
https://pastebin.com/0NQDfAcv

**Comment by gudenau** [comment]
Man that's a weird one, should be fixable though.

**Comment by gudenau** [comment]
[Test.zip](https://github.com/gudenau/minecraft-MoreTags/files/8954858/Test.zip)

Could you try this build out?

**Comment by gudenau** [comment]
Could you try this out and give me the logs? It should still crash but this should give me more information to work off of.

[test.zip](https://github.com/gudenau/minecraft-MoreTags/files/8961053/test.zip)
