### ISSUE TITLE
breaks ecologics

### ISSUE THREAD

**Issue by FluffyBumblebees** [gudenau/minecraft-MoreTags#18]
1.18.2 / 0.14.8 / 0.56.1
[latest.log](https://github.com/gudenau/minecraft-MoreTags/files/8997923/latest.log)

**Comment by gudenau** [comment]
This is quite strange, Ecologics doesn't seem to touch my redirect.

**Comment by gudenau** [comment]
[Could you try this jar?](https://github.com/gudenau/minecraft-MoreTags/files/8961053/test.zip)

**Comment by FluffyBumblebees** [comment]
[latest.log](https://github.com/gudenau/minecraft-MoreTags/files/9006431/latest.log)
Still same error...

**Comment by FluffyBumblebees** [comment]
actually it is a different error, now farmland is crashing...

**Comment by FluffyBumblebees** [comment]
the ecologics issue seems to be fixed, the farmland just needs a different entrypoint

**Comment by FluffyBumblebees** [comment]
nvm it still had the same issue

**Comment by gudenau** [comment]
I honestly can't figure out what the problem is here.

**Comment by gudenau** [comment]
Oh, I think I see what might be going on here.

**Comment by FluffyBumblebees** [comment]
What is it?

**Comment by gudenau** [comment]
I fixed the first issue and found a second. How nice.

**Comment by gudenau** [comment]
At this point this is now a case of "they are using a redirect when they don't have to", I did what I can do. As fixed as possible in v3.0.7.
