### ISSUE TITLE
[Question] Why doesn't this use the 'c' namespace?

### ISSUE THREAD

**Issue by supersaiyansubtlety** [gudenau/minecraft-MoreTags#6]
It seems like all the tags in this mod would fit perfectly into the common 'c' namespace, used by other mods and datapacks.

**Comment by gudenau** [comment]
I didn't know that was a thing.

**Comment by supersaiyansubtlety** [comment]
Would you consider adding the tags under both namespaces?

Keeping 'moretags' keeps backwards compatibility, while 'c' can "automatically" facilitate cross mod compatibility when other mods (not necessarily even aware of MoreTags) use the namespace.

**Comment by supersaiyansubtlety** [comment]
Saw the 2.0.0 update, thanks!
